experiment_name: YOLOX
config_name: 'dark_s-FPN'
backbone: 'dark_s'
neck: 'FPN'
act: 'lrelu'

optimizer: 'adamW'
scheduler: 'OneCycleLR'

lr: 0.0001
batch_size: 2
epoch: 10
num_workers: 1

aug: True
augmentation_type: 'det'
aug_dicts:
  affine: 
    translate_percent: [-0.05, 0.05]
    scale: [0.5, 1.5]
    rotate: [-5, 5]
    mode: 'constant'
    cval: [200, 255]
  fliplr:
    p: 0.5
  flipud:
    p: 0.5
  addgaussiannoise: 
    loc: 0
    scale: [0.0, 8.0]
    per_channel: 0.5
  multiply:    
    mul: [0.4, 1.5]
  cutout:       
    nb_iterations: [2, 6]
    size: 0.05
    squared: False
    fill_mode: "constant"
    cval: [0, 255]
    fill_per_channel: 0.5
  add:    
    value: [-40, 40]
    per_channel: 0.5
  grayscale:      
    alpha: [0.5, 1.0]
  gaussianblur:               
    sigma: [0.6,1.4]

input_size: (512, 512)     

dataset_name: 'Coco'
training_mission: 'det'
num_classes: 80
data_dir: '/home/shaoran/Datasets/coco2017/'

json_file: 'instances_val2017.json'
name: 'val2017'

json_file_val: 'instances_val2017.json'
name_val: 'val2017'
loss_criteria: True