experiment_name: ICT
backbone: 'res_18'
d_model: 512
num_heads: 8
dff: 1024
num_layers: 2
target_vocab_size: 1426
max_length: 50
pad_index: 1

optimizer: 'adamW'
scheduler: 'OneCycleLR'

lr: 0.001
batch_size: 2
epoch: 10
num_workers: 0

aug: False
augmentation_type: 'det'

input_size: (64, 320)
num_channel: 3

dataset_name: 'IC'

images_dir: '/home/shaoran/datasets/starsee/formula/rec/files/latex10k_test_v1_songti/images'
labels_dir: '/home/shaoran/datasets/starsee/formula/rec/files/latex10k_test_v1_songti/matching.txt'
chars_file: '/home/shaoran/datasets/starsee/formula/rec/files/vocab.txt'

images_dir_val: '/home/shaoran/datasets/starsee/formula/rec/files/latex10k_test_v1_songti/images'
labels_dir_val: '/home/shaoran/datasets/starsee/formula/rec/files/latex10k_test_v1_songti/matching.txt'


