experiment_name: DB
config_name: 'mobilevit_xxs-PAFPN-640x640'
backbone: 'mobilevit_xxs'
neck: 'PAFPN'

optimizer: 'adamW'
scheduler: 'OneCycleLR'

lr: 0.001
batch_size: 2
epoch: 10
num_workers: 1

aug: True
augmentation_type: 'polygon'
aug_dicts:
  affine: 
    translate_percent: [-0.05, 0.05]
    scale: [0.5, 1.5]
    rotate: [-5, 5]
    mode: 'constant'
    cval: [200, 255]
  fliplr:
    p: 0.5
  flipud:
    p: 0.5
  addgaussiannoise:            
    loc: 0
    scale: [0.0, 8.0]
    per_channel: 0.5
  multiply:          
    mul: [0.4, 1.5]
  grayscale:     
    alpha: [0.5, 1.0]
  gaussianblur:   
    sigma: [0.6,1.4]


input_size: (640, 640)

dataset_name: 'OcrDet'
train_list: ['/home/shaoran/datasets/OCR/DET/datasets/test/img', '/home/shaoran/datasets/OCR/DET/datasets/test/gt']
test_list: ['/home/shaoran/datasets/OCR/DET/datasets/test/img', '/home/shaoran/datasets/OCR/DET/datasets/test/gt']