experiment_name: MaskFormer
config_name: 'mobilenetv3_s'
backbone: 'mobilenetv3_s'

optimizer: 'adamW'
scheduler: 'OneCycleLR'

lr: 0.0001
batch_size: 2
epoch: 10
num_workers: 2

aug: True
augmentation_type: 'seg'
aug_dicts:
  affine: 
    translate_percent: [-0.2, 0.2]
    scale: [0.5, 1.5]
    rotate: [-5, 5]
    mode: 'constant'
    cval: [200, 255]
  fliplr:
    p: 0.5
  flipud:
    p: 0.5
  multiply:               
    mul: [0.9, 1.1]
  gaussianblur:
    sigma: [0.9,1.1]


input_size: (512, 512)  

dataset_name: 'Coco_stff_10k'
data_dir: '/home/shaoran/datasets/coco/coco_stuff_10k'
num_classes: 171

loss_criteria: True